"""Tests for the server → agent reply bridge in agent.py.

BattleBuddy's voice reply is generated by bb-server (/session/turn) and pushed
into the LiveKit room as a `bb.speak` data packet; the agent's only job is to
speak it. parse_speak_packet is the whole decision — which packets become
speech and which are ignored — so it is the piece worth testing.

Why source-level tests matter here specifically: the handler that calls this
lives inside the session closure, where neither CI gate can reach it. The
compile gate parses without executing; the import gate executes module-level
code only. That blind spot is how an in-method import shipped green and killed
voice for 18 hours (PR #101 → #120). Keeping the logic at module level is what
makes it testable at all — these tests fail if it moves back inside.
"""

import re
from pathlib import Path

import agent

AGENT_SOURCE = (Path(__file__).parent.parent / "agent.py").read_text()


def _packet(payload_bytes, topic=agent.SPEAK_TOPIC):
    return topic, payload_bytes


def _speak_bytes(text, msg_id=None):
    import json
    body = {"type": "speak", "text": text}
    if msg_id:
        body["id"] = msg_id
    return json.dumps(body).encode("utf-8")


def test_speak_packet_yields_the_text():
    topic, data = _packet(_speak_bytes("Hey, glad you're here."))
    assert agent.parse_speak_packet(topic, data, set()) == "Hey, glad you're here."


def test_other_topics_are_ignored():
    """The client publishes its own data (the bare string VOICE_FAILURE) on the
    default topic — speaking that aloud would be a bug."""
    assert agent.parse_speak_packet(None, b"VOICE_FAILURE", set()) is None
    assert agent.parse_speak_packet("other", _speak_bytes("nope"), set()) is None


def test_malformed_payloads_are_ignored_not_raised():
    """A data handler that raises takes the room's event loop with it."""
    seen = set()
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, b"not json", seen) is None
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, b"[1,2,3]", seen) is None
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, b'{"type":"other"}', seen) is None


def test_typeless_payload_from_the_previously_shipped_server_is_accepted():
    """bb-server and bb-agent deploy as separate Railway services. PR #125's
    server sends a bare {"text": …}; a new agent must still speak it or voice
    goes silent for the width of the deploy window."""
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, b'{"text":"still here"}', set()) == "still here"


def test_empty_and_whitespace_text_is_ignored():
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, _speak_bytes(""), set()) is None
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, _speak_bytes("   \n "), set()) is None


def test_text_is_stripped():
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, _speak_bytes("  hi  "), set()) == "hi"


def test_repeated_id_is_spoken_only_once():
    """LiveKit reliable delivery can repeat a packet. Speaking the same reply
    twice is the exact double-answer this architecture exists to prevent."""
    seen = set()
    data = _speak_bytes("You've got this.", msg_id="turn-1")
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, data, seen) == "You've got this."
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, data, seen) is None


def test_distinct_ids_both_speak():
    seen = set()
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, _speak_bytes("one", "a"), seen) == "one"
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, _speak_bytes("two", "b"), seen) == "two"


def test_bytearray_and_memoryview_payloads_decode():
    """LiveKit hands the handler bytes today; don't break if it hands a buffer."""
    raw = _speak_bytes("buffered")
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, bytearray(raw), set()) == "buffered"
    assert agent.parse_speak_packet(agent.SPEAK_TOPIC, memoryview(raw), set()) == "buffered"


def test_agent_never_generates_its_own_reply():
    """The single-brain invariant. If a generate_reply() call comes back, the
    user gets answered twice by two different models — once in text from
    /session/turn and once, differently, in voice."""
    assert "session.generate_reply(" not in AGENT_SOURCE, (
        "the voice agent must not generate replies — bb-server is the reply source"
    )
    assert re.search(r"raise StopResponse\(\)", AGENT_SOURCE), (
        "on_user_turn_completed must raise StopResponse or the agent-side LLM runs"
    )


def test_bridge_logic_stays_at_module_level():
    """Guards the testability that the CI gates depend on."""
    assert re.search(r"^def parse_speak_packet\(", AGENT_SOURCE, re.M)
    assert re.search(r"^SPEAK_TOPIC = ", AGENT_SOURCE, re.M)
