-- Session reports: structured AI analysis of each session, generated server-side.
-- Fed into profile builder for personalization.

create table public.session_reports (
  id                uuid primary key default uuid_generate_v4(),
  craving_event_id  uuid not null references public.craving_events(id) on delete cascade,
  user_id           uuid not null references public.users(id) on delete cascade,
  created_at        timestamptz not null default now(),

  -- Structured analysis (generated by Claude)
  trigger_type      text,                    -- stress, boredom, social, routine, craving
  trigger_intensity smallint,                -- 1-5
  outcome           text,                    -- resisted, submitted, unsure
  emotional_arc     jsonb not null default '{}',  -- { start: "anxious", end: "calm" }
  what_helped       text[],                  -- ["encouragement framing", "wave exercise"]
  what_didnt_help   text[],                  -- ["distraction", "consequences framing"]
  preferences       jsonb not null default '{}',  -- { preferred_mode: "voice", coping_style: "talk-through" }
  next_session_hint text,                    -- "Try wave exercise earlier; user responds to direct questions"
  summary           text not null            -- 1-2 sentence natural language summary
);

alter table public.session_reports enable row level security;

create policy "session_reports: own rows only"
  on public.session_reports for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index on public.session_reports (user_id, created_at desc);
create unique index on public.session_reports (craving_event_id);
